url: https://money.humanwhocodes.com
name: Human Who Codes Money
description: Personal finance, investing, and real estate.
markdown: kramdown
permalink: /blog/:year/:month/:title/
future: false
paginate: 10
paginate_path: /blog/page/:num/
feed_source: /feeds/blog.xml
json_feed_source: /feeds/blog.json
include:
  - _redirects
plugins:
    - jekyll-sitemap
    - jekyll-redirect-from
    - jekyll-archives
    - jekyll-email-protect

kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
  parse_block_html: true

jekyll-archives:
  enabled:
    - year
    - month
    - tags
  layouts:
    year: year-archive
    month: month-archive
    tag: tag-archive
  permalinks:
    year: '/blog/:year/'
    month: '/blog/:year/:month/'
    tag: '/blog/tag/:name/'
